version: '3.9'

services:
  webapp:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDER_VERIFIED: ${SENDER_VERIFIED}
      DOMAIN: ${DOMAIN}
      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      cloud_name: ${cloud_name}
      api_key: ${api_key}
      api_secret: ${api_secret}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      VITE_STRIPE_PUBLISH_KEY: ${VITE_STRIPE_PUBLISH_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}